export const HOTEL_REQUEST = "STAY/HOTEL_REQUEST";
export const HOTEL_FAILURE = "STAY/HOTEL_FAILURE";

export const GET_HOTEL_SUCCESS = "STAY/GET_HOTEL_SUCCESS";
export const POST_HOTEL_SUCCESS = "STAY/POST_HOTEL_SUCCESS";

export const NEW_GET_HOTELS_SUCCESS = "STAY/NEW_GET_HOTELS_SUCCESS";
export const DELETE_HOTEL = "STAY/DELETE_HOTEL";
export const SELECTED_DATE_AND_CITY = "SELECTED_DATE_AND_CITY";
export const SELECTED_CITY = "SELECTED_CITY";
